name: Apply Terraform

on:
  push:
    branches:
      - main

      
jobs:
  terraform:
    uses: gabriellmb05/terraform-ci/.github/workflows/terraform.yaml@main
    with:
      working_directory: infra
      environment: prod
    secrets:
      TF_VAR_PASSWORD: ${{ secrets.TF_VAR_PASSWORD }}
      aws_assume_role_arn: ${{ secrets.aws_assume_role_arn }}